### ISSUE TITLE
Players can place blocks inside themselves

### ISSUE THREAD

**Issue by calumari** [Phoenix616/RandomTeleport#37] opened 2020-05-28 09:41 UTC
Hey, this may be an issue with Paper but I'm running it by you first. Players can place blocks inside themselves shortly after /rtp'ing.

The issue is fairly difficult to reproduce so here's a video: https://streamable.com/pufntq . I haven't been able to reproduce it in generated chunks yet.

Running Paper 321
Plugins: RandomTeleport 2.0-SNAPSHOT (build 63)

**Comment by calumari** [comment] 2020-05-28 09:53
I tried reproducing the issue with this on a flat world with no joy.
`player.teleportAsync(new Location(player.getWorld(), ThreadLocalRandom.current().nextInt(100000) + .5, 4, ThreadLocalRandom.current().nextInt(100000) + .5))`

Howevever, I did noticed that the chunk returned by RandomSearcher is unloaded after teleporting targets.

**Comment by Phoenix616** [comment] 2020-05-28 10:27
I highly doubt this is caused by this plugin, all it does is use paper's api for loading the chunks async and teleport once loaded. If this is happening then there is an issue in the server not registering the new player position correctly which would've to be fixed in the server itself.

But what do you jean by 

> I did noticed that the chunk returned by RandomSearcher is unloaded after teleporting targets.

The plugin is not unloading anything and the found chunk is directly used for teleporting without any delay. If it would unload it async in the same tick as it was loaded then that would be a huge server issue. I highly recommend reporting it to them with some basic code to reproduce this unloading behaviour.

**Comment by calumari** [comment] 2020-05-28 10:31
Give me a bit and I'll write up a small plugin to reproduce this issue.

**Closed** 2020-05-29 03:26 UTC
Labels: server issue
